---
abstract: 'Mason 2.x wrapper for Dancer'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Dancer::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Template-Mason2
requires:
  Dancer::Config: 0
  Dancer::Template::Abstract: 0
  FindBin: 0
  Mason: 2.00
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dancer-Template-Mason2
  repository: git://github.com/jonswar/perl-dancer-template-mason2.git
version: 0.01
